import type { Config } from "tailwindcss";

// Design tokens extracted verbatim from the Stitch export
// (stitch_gokavi_hospital_admin_dashboard/d1_clinical_minimal_*/code.html)
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        secondary: "#a93349",
        "surface-tint": "#5b598c",
        "on-surface-variant": "#47464f",
        "on-tertiary-fixed": "#21005e",
        "on-secondary-container": "#730425",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdadc",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c4c1fb",
        "on-secondary-fixed": "#400010",
        surface: "#f7f9fb",
        "inverse-primary": "#c4c1fb",
        tertiary: "#0f0034",
        "on-primary-fixed": "#181445",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#4f319c",
        "surface-container-low": "#f2f4f6",
        "surface-variant": "#e0e3e5",
        "on-primary": "#ffffff",
        "secondary-container": "#fe7488",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb2b9",
        "inverse-surface": "#2d3133",
        primary: "#070235",
        "on-tertiary-container": "#9377e4",
        "on-background": "#191c1e",
        "outline-variant": "#c8c5d0",
        "inverse-on-surface": "#eff1f3",
        "on-surface": "#191c1e",
        background: "#f7f9fb",
        "on-primary-container": "#8683ba",
        "primary-container": "#1e1b4b",
        "on-secondary-fixed-variant": "#891933",
        "on-primary-fixed-variant": "#444173",
        "primary-fixed": "#e3dfff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#28006e",
        "tertiary-fixed-dim": "#cebdff",
        outline: "#787680",
        "tertiary-fixed": "#e8ddff",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "surface-dim": "#d8dadc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-gap": "16px",
        "container-padding-desktop": "48px",
        "container-padding-mobile": "20px",
        gutter: "24px",
        base: "8px",
        "sidebar-width": "16rem",
      },
      fontFamily: {
        sans: ["var(--font-dm-sans)", "DM Sans", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-dm-sans)", "DM Sans"],
        "headline-md": ["var(--font-dm-sans)", "DM Sans"],
        "body-lg": ["var(--font-dm-sans)", "DM Sans"],
        "body-md": ["var(--font-dm-sans)", "DM Sans"],
        button: ["var(--font-dm-sans)", "DM Sans"],
        "headline-lg-mobile": ["var(--font-dm-sans)", "DM Sans"],
        "label-caps": ["var(--font-dm-sans)", "DM Sans"],
      },
      fontSize: {
        "headline-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        button: ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "30px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
